### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by ricvee** [JanJaapKo/domoticz-GoodWeSEMS#19]
Hi,
I have used the older plugin before, deleted it, restarted domoticz, installed your plugin, restarted domoticz.
I entered my credentials in the Hardware tab, and now I see this in the logs:

 2022-12-27 16:49:17.594 Error: ZP: (GoodWeSEMS) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2022-12-27 16:49:17.616 Error: ZP: Traceback (most recent call last):
2022-12-27 16:49:17.616 Error: ZP: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 77, in <module>
2022-12-27 16:49:17.616 Error: ZP: from GoodWe import GoodWe
2022-12-27 16:49:17.616 Error: ZP: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/GoodWe.py", line 28, in <module>
2022-12-27 16:49:17.616 Error: ZP: import requests
2022-12-27 16:49:17.616 Error: ZP: ModuleNotFoundError: No module named 'requests' 

There are no new devices to be seen.
Can you help me?

**Comment by ricvee** [comment]
Over Domoticz
Version: 2022.2
Build Hash: eea9db734
Compile Date: 2022-11-05 13:05:35
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

**Comment by JanJaapKo** [comment]
Oops sorry. I updated the plugin by using the requests library for more elegant handling of the web requests but forgot to update the installation instructions. They're updated now, can you give it another try?

Basically, this should be enough:
```
sudo apt-get update
sudo apt-get install python3-requests
sudo systemctl restart domoticz
```

**Comment by ricvee** [comment]
Thanks, that did the trick for me!
Another question:
Shouldn´t be the sum of my two strings Inverter input 1 and 2 pwr , the same as the Inverter Output Power?
As you can see it is not at this moment.
![afbeelding](https://user-images.githubusercontent.com/40305032/210621406-38db4e1e-abae-414e-8877-7b637379960c.png)

**Comment by JanJaapKo** [comment]
Well no. Firstly, the input powers an average over your refesh interval whereas the output should really accumulate. Then secondly, there would be some internal losses. So the output should be accurate, the input is just an indication to the ratio between the strings.
