### ISSUE TITLE
After update trying to convert database

### ISSUE THREAD

**Issue by PvdGulik** [JanJaapKo/domoticz-GoodWeSEMS#25]
**Describe the bug**
Updated the plugin, found some errors in the log. 

2023-11-15 22:04:36.628 Error: GoodWe GW5000-DT: Call to function 'onStart' failed, exception details:
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: Traceback (most recent call last):
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 620, in onStart
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: _plugin.onStart()
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 337, in onStart
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: self.startDeviceUpdateV2()
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 150, in startDeviceUpdateV2
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: self.updateDevices(DeviceData)
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 158, in updateDevices
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: self.createDevices(inverter["sn"])
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 217, in createDevices
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: numDevs = len(Devices[serialNumber].Units)
2023-11-15 22:04:36.631 Error: GoodWe GW5000-DT: KeyError: '95000DTU193W0183'

Found out on this Github-page I have to convert the database.
Followed the instructions, but on import I got a error...

**To Reproduce**
After convert the ID's

pi@Domoticz:~/domoticz $ sqlite3 domoticz.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> DROP TABLE IF EXISTS DeviceStatus;
sqlite> .mode csv
sqlite> .separator ";"
sqlite> .import devicedata.csv
ERROR: missing TABLE argument. Usage:
.import FILE TABLE       Import data from FILE into TABLE
   Options:
     --ascii               Use \037 and \036 as column and row separators
     --csv                 Use , and \n as column and row separators
     --skip N              Skip the first N rows of input
     -v                    "Verbose" - increase auxiliary output
   Notes:
     *  If TABLE does not exist, it is created.  The first row of input
        determines the column names.
     *  If neither --csv or --ascii are used, the input mode is derived
        from the ".mode" output mode
     *  If FILE begins with "|" then it is a command that generates the
        input text.

**Expected behavior**
That import would work as supposed

**Screenshots**
pi@Domoticz:~/domoticz $ sqlite3 domoticz.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> DROP TABLE IF EXISTS DeviceStatus;
sqlite> .mode csv
sqlite> .separator ";"
sqlite> .import devicedata.csv
ERROR: missing TABLE argument. Usage:
.import FILE TABLE       Import data from FILE into TABLE
   Options:
     --ascii               Use \037 and \036 as column and row separators
     --csv                 Use , and \n as column and row separators
     --skip N              Skip the first N rows of input
     -v                    "Verbose" - increase auxiliary output
   Notes:
     *  If TABLE does not exist, it is created.  The first row of input
        determines the column names.
     *  If neither --csv or --ascii are used, the input mode is derived
        from the ".mode" output mode
     *  If FILE begins with "|" then it is a command that generates the
        input text.

**Domoticz environment (please complete the following information):**
 - Domoticz V2023.2 (build 15650)
 - Python version '3.9.2',

**Additional context**

**Comment by JanJaapKo** [comment]
Sorry missed the table name in the import. Wiki updated, please try the import steps again.

**Comment by PvdGulik** [comment]
Oke, that helped a bit.. but now following errors...

2023-11-15 22:43:27.834 Status: GoodWe GW5000-DT: Entering work loop.
2023-11-15 22:43:27.834 Status: GoodWe GW5000-DT: Started.
2023-11-15 22:43:27.840 Status: dzVents: Write file: /home/pi/domoticz/scripts/dzVents/generated_scripts/PVOutput Goodwe.lua
2023-11-15 22:43:30.407 Status: GoodWe GW5000-DT: Initialized version 4.0.0, author 'Jan-Jaap Kostelijk'
2023-11-15 22:43:30.432 Status: GoodWe GW5000-DT: Starting Goodwe SEMS API plugin, logging to file goodwe GoodWe GW5000-DT.log
2023-11-15 22:43:31.518 GoodWe GW5000-DT: Status of GoodWe inverter (SN: 95000DTU193W0183): '-1 offline'
2023-11-15 22:43:31.520 Error: GoodWe GW5000-DT: Update to 'UnitEx' failed to update any DeviceStatus records for key 21/95000DTU193W0183/4
2023-11-15 22:43:31.535 Error: GoodWe GW5000-DT: Call to function 'onStart' failed, exception details:
2023-11-15 22:43:31.541 Error: GoodWe GW5000-DT: Traceback (most recent call last):
2023-11-15 22:43:31.541 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 620, in onStart
2023-11-15 22:43:31.541 Error: GoodWe GW5000-DT: _plugin.onStart()
2023-11-15 22:43:31.541 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 337, in onStart
2023-11-15 22:43:31.541 Error: GoodWe GW5000-DT: self.startDeviceUpdateV2()
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 150, in startDeviceUpdateV2
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: self.updateDevices(DeviceData)
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 182, in updateDevices
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: newCounter = calculateNewEnergy(inverter["sn"], theInverter.inputPower1Unit, inputPower)
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: File "/home/pi/domoticz/plugins/domoticz-GoodWeSEMS/plugin.py", line 605, in calculateNewEnergy
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: lastUpdateDT = datetime.fromtimestamp(time.mktime(time.strptime(dt_string, dt_format)))
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: tt = _strptime(data_string, format)[0]
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: raise ValueError("time data %r does not match format %r" %
2023-11-15 22:43:31.542 Error: GoodWe GW5000-DT: ValueError: time data '15-11-2023 21:12' does not match format '%Y-%m-%d %H:%M:%S'

following with a lot of lines with:

2023-11-15 22:44:07.176 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.177 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.178 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.180 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.181 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.182 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.184 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.198 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.199 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:07.201 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:12.182 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:12.189 Error: Serious database error, problem getting ID from DeviceStatus!
2023-11-15 22:44:12.191 Error: Serious database error, problem getting ID from DeviceStatus!

**Comment by PvdGulik** [comment]
I restored my database with the old ID’s. But the new plugin is still installed. How to rollback to the previous plugin?

thanks!

**Comment by JanJaapKo** [comment]
not really sure how to properly do it, but a simple way is to download the previous versions of the files and place them on your PI (unfortunately I did make a version in GIT, that would have made this easier......)

**Comment by JanJaapKo** [comment]
ok, it looks like the import of the DeviceStatus was not successful. To check that the import was actually succesful, you can check, after the `.import devicedata.csv DeviceStatus` (so still in sqlite)

`select * from DeviceStatus;`
Or
`select * from DeviceStatus where HardwareID=xx; `

where you need to replace xx with the hardware number from your inverter (can be found on the Hardware page in Domoticz, in the first column under Idx). It should then show the devices for the inverter with the serial number. See below screenshot from my setup:
![image](https://github.com/JanJaapKo/domoticz-GoodWeSEMS/assets/44156144/6d75cb1a-635a-4b36-8a16-f3481e77b279)

**Comment by PvdGulik** [comment]
I changed all the devices connected by hardware ID21 to the corresponding serialnr. of the GoodWe inverter.
See included picture, and did the second part, importing the devicedata.csv back into the database.

<img width="1371" alt="Scherm­afbeelding 2023-11-16 om 21 29 37" src="https://github.com/JanJaapKo/domoticz-GoodWeSEMS/assets/9421474/70e9d8b9-266f-4665-bcdf-fe6c79a7fdd7">

After that, Domoticz does not start any more...

Tried your suggested checks, seems to be good..
<img width="1211" alt="Scherm­afbeelding 2023-11-16 om 21 37 05" src="https://github.com/JanJaapKo/domoticz-GoodWeSEMS/assets/9421474/843d369c-2aaf-4347-bed3-950606ae2d59">

After disabling the hardware Id with `sudo sqlite3  -header -list domoticz.db "UPDATE Hardware set Enabled = 0 where ID = 21"` Domoticz is running again, without the GoodWe hardware ;-(

Still not have a solution ..... please help

**Comment by JanJaapKo** [comment]
The devices seem to be present 2 times, that is not necesarily a good idea. But when it works..........

**Comment by PvdGulik** [comment]
> The devices seem to be present 2 times, that is not necesarily a good idea. But when it works..........

No, it does not. Which ones should I remove?

**Comment by JanJaapKo** [comment]
Does not matter, it is only the definition, and they're equal.

**Comment by PvdGulik** [comment]
I'm back to the previous version. Cannot get it working...

**Comment by MrHobbes74** [comment]
I just installed this plugin for the first time (no history with old devices) and I get the same error as the first post in this thread (keyerror). It seems that the creation devices when they do not yet exist is not working correctly!

**Comment by PvdGulik** [comment]
I'm still using the old version which still works..

**Comment by JanJaapKo** [comment]
OK, I see where it goes wrong for a clean install, preparing a fix. Thought I had this tested, but it apparently wasn't on a fully clean install....

<update> I'm struggling with creating new devices (or units) in the plugin framework, awaiting advise from forum

**Comment by MrHobbes74** [comment]
old version indeed works fine, which I have installed now.
